//@ui5-bundle pmsopenui5test/pmsopenui5test/Component-preload.js
sap.ui.require.preload({
	"pmsopenui5test/pmsopenui5test/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","pmsopenui5test/pmsopenui5test/model/models"],function(e,t,i){"use strict";return e.extend("pmsopenui5test.pmsopenui5test.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"pmsopenui5test/pmsopenui5test/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("pmsopenui5test.pmsopenui5test.controller.App",{onInit:function(){}})});
},
	"pmsopenui5test/pmsopenui5test/controller/View1.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("pmsopenui5test.pmsopenui5test.controller.View1",{onInit:function(){},onPressPA:function(e){debugger;let n=this.getView().byId("mobno").getValue();let t=this.getView().byId("lname").getValue();let i=this.getView().byId("fname").getValue();if(n==null||n==""||n==undefined||(t==null||t==""||t==undefined)||(i==null||i==""||i==undefined)){sap.m.MessageBox.error("Please fill the Required fields")}else{}}})});
},
	"pmsopenui5test/pmsopenui5test/controller/View2.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("pmsopenui5test.pmsopenui5test.controller.View2",{onInit:function(){let e=new t;e.setProperty("/patient",[{PID:"907809",FNAME:"Mohammad",LNAME:"Acharya",MOBNO:"88909090"},{PID:"454634",FNAME:"Vinay",LNAME:"Kothari",MOBNO:"78890000"}]);this.getView().setModel(e,"patients")},onChangeMobNo:function(e){debugger;if(!(this.getView().byId("mobno").getValue()==""||this.getView().byId("mobno").getValue()==null||this.getView().byId("mobno").getValue()==undefined)){this.getView().byId("fname").setBlocked(true);this.getView().byId("lname").setBlocked(true)}else{if(this.getView().byId("mobno").getValue()==""){}this.getView().byId("fname").setBlocked(false);this.getView().byId("lname").setBlocked(false)}var t=new sap.ui.model.Filter("MOBNO",sap.ui.model.FilterOperator.Contains,this.getView().byId("mobno").getValue());this.getView().byId("idPatientTable").getBinding("items").filter(t)},onChangeFName:function(e){debugger;this.ValidateName("fname","mobno");var t=new sap.ui.model.Filter("FNAME",sap.ui.model.FilterOperator.Contains,this.getView().byId("fname").getValue());this.getView().byId("idPatientTable").getBinding("items").filter(t)},onChangeLName:function(e){debugger;this.ValidateName("lname","mobno")},ValidateName:function(e,t){if(!(this.getView().byId(e).getValue()==""||this.getView().byId(e).getValue()==null||this.getView().byId(e).getValue()==undefined)){this.getView().byId(t).setBlocked(true);if(!/^[a-zA-Z]+$/.test(this.getView().byId(e).getValue())){this.getView().byId(e).setValueState("Error")}else{this.getView().byId(e).setValueState("None")}}else{switch(e){case"fname":if(this.getView().byId("lname").getValue()==""||this.getView().byId("lname").getValue()==null||this.getView().byId("lname").getValue()==undefined){this.getView().byId(t).setBlocked(false)}else{this.getView().byId(t).setBlocked(true)}break;case"lname":if(this.getView().byId("fname").getValue()==""||this.getView().byId("fname").getValue()==null||this.getView().byId("fname").getValue()==undefined){this.getView().byId(t).setBlocked(false)}else{this.getView().byId(t).setBlocked(true)}break}}},onSearch:function(e){debugger;var t=new sap.ui.model.Filter("MOBNO",sap.ui.model.FilterOperator.Contains,this.getView().byId("mobno").getValue());var i=new sap.ui.model.Filter([oFilter1,oFilter2,t],false);this.getView().byId("idPatientTable").getBinding("items").filter(i)}})});
},
	"pmsopenui5test/pmsopenui5test/controller/View_Main.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("pmsopenui5test.pmsopenui5test.controller.View_Main",{onInit:function(){},CreatePatient:function(e){debugger;this.getOwnerComponent().getRouter().navTo("RouteView1")},ViewPatient:function(e){debugger;this.getOwnerComponent().getRouter().navTo("RouteView2")}})});
},
	"pmsopenui5test/pmsopenui5test/i18n/i18n.properties":'# This is the resource bundle for pmsopenui5test.pmsopenui5test\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=PMS Test\n\n#YDES: Application description\nappDescription=Patient Management System\r\n#XTIT: Main view title\ntitle=PMS Test',
	"pmsopenui5test/pmsopenui5test/manifest.json":'{"_version":"1.59.0","sap.app":{"id":"pmsopenui5test.pmsopenui5test","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.13.0","toolsId":"77a88599-a893-45c7-9a1d-c506fcdf9c05"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.122.0","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"pmsopenui5test.pmsopenui5test.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"pmsopenui5test.pmsopenui5test.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView_Main","pattern":":?query:","target":["TargetView_Main"]},{"name":"RouteView1","pattern":":Page1","target":["TargetView1"]},{"name":"RouteView2","pattern":"Page2","target":["TargetView2"]}],"targets":{"TargetView_Main":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View_Main","viewName":"View_Main"},"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"},"TargetView2":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View2","viewLevel":1,"viewName":"View2"}}},"rootView":{"viewName":"pmsopenui5test.pmsopenui5test.view.App","type":"XML","async":true,"id":"App"}}}',
	"pmsopenui5test/pmsopenui5test/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"pmsopenui5test/pmsopenui5test/view/App.view.xml":'<mvc:View controllerName="pmsopenui5test.pmsopenui5test.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"pmsopenui5test/pmsopenui5test/view/View1.view.xml":'<mvc:View controllerName="pmsopenui5test.pmsopenui5test.controller.View1"\n    xmlns:l="sap.ui.layout"\n    xmlns:f="sap.ui.layout.form"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><Page id="page" title="Patient Registration Form"><VBox class="sapUiSmallMargin"><f:Form id="FormToolbar" editable="true" layout="ResonsiveGridLayout" ariaLabelledBy="Title1"><f:layout><f:ResponsiveGridLayout labelSpanXL="4" labelSpanL="3" labelSpanM="4" labelSpanS="12" adjustLabelSpan="false" emptySpanXL="0" emptySpanL="4" emptySpanM="0" emptySpanS="0" columnsXL="2" columnsL="1" columnsM="1" singleContainerFullSize="false" /></f:layout><f:formContainers><f:FormContainer ariaLabelledBy="Title2"><f:toolbar><Toolbar><Title id="Title2" text="Enter Patient Details" /><ToolbarSpacer /></Toolbar></f:toolbar><f:formElements><f:FormElement label="Patient ID"><f:fields><Input value="{patient>/PID}" id="pid" width="100px"  enabled="false" /></f:fields></f:FormElement><f:FormElement label="First Name"><f:fields><Input value="{patient>/FNAME}" id="fname" required="true" width="300px"/></f:fields></f:FormElement><f:FormElement label="Last Name"><f:fields><Input value="{patient>/LNAME}" id="lname" required="true" width="300px"/></f:fields></f:FormElement><f:FormElement label="Sex"><f:fields><Select id="selectSex" change="onSelectChangeCurr"><layoutData><l:GridData span="XL2 L3 M3 S4" /></layoutData><items><core:Item key="M" text="M : Male"/><core:Item key="F" text="F : Female"/></items></Select></f:fields></f:FormElement><f:FormElement label="Mobile No" ><f:fields><Input value="{patient>/MOBNO}"  id="mobno" width="300px" required="true"  type="Number"/></f:fields></f:FormElement></f:formElements></f:FormContainer></f:formContainers></f:Form></VBox><footer><Bar><contentRight><Button id="Create_Pat" type="Accept" text="Register" press="onPressPA" enabled="true"/><Button type="Accept" text="Clear" press="onPressClear" /></contentRight></Bar></footer></Page></mvc:View>\n',
	"pmsopenui5test/pmsopenui5test/view/View2.view.xml":'<mvc:View controllerName="pmsopenui5test.pmsopenui5test.controller.View2"\n\txmlns:l="sap.ui.layout"\n\txmlns:f="sap.ui.layout.form"\n\txmlns:fb="sap.ui.comp.filterbar"\n\txmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n\txmlns="sap.m"><Page id="page" title="View Patients"><Panel headerText="Search Patients" expandable="true" width="auto" class="sapUiResponsiveMargin"><content><fb:FilterBar id="filterbar" persistencyKey="myPersKey" useToolbar="false" search="onSearch" filterChange=".onFilterChange" afterVariantLoad=".onAfterVariantLoad"><fb:filterGroupItems><fb:FilterGroupItem name="Carrid" label="Mobile No" groupName="Group1" visibleInFilterBar="true"><fb:control><Input value="{patient>/MOBNO}" id="mobno" width="300px" liveChange="onChangeMobNo"  type="Number"  /></fb:control></fb:FilterGroupItem><fb:FilterGroupItem name="First Name" label="First Name" groupName="Group1" visibleInFilterBar="true"><fb:control><Input value="{patient>/FNAME}" id="fname" width="300px" liveChange="onChangeFName"/></fb:control></fb:FilterGroupItem><fb:FilterGroupItem name="Last Name" label="Last Name" groupName="Group1" visibleInFilterBar="true"><fb:control><Input value="{patient>/LNAME}" id="lname" width="300px" liveChange="onChangeLName" /></fb:control></fb:FilterGroupItem></fb:filterGroupItems></fb:FilterBar></content></Panel><content><Panel headerText="Patients Found" expandable="false" width="auto" class="sapUiResponsiveMargin"><VBox class="sapUiTinyMargin"><Table id="idPatientTable" class="sapUiResponsiveLayout" items="{patients>/patient}" growingThreshold="10"><infoToolbar><OverflowToolbar><Label text="Patients" /><ToolbarSpacer /><Button id="ref1" text="Refresh" press="onPressRF" icon="sap-icon://refresh" tooltip="Refresh"  enabled="{Refbutton>/enable}" /></OverflowToolbar></infoToolbar><columns><Column width="12em"><Text text="Patient ID" /></Column><Column minScreenWidth="Tablet" demandPopin="true"><Text text="First Name" /></Column><Column minScreenWidth="Tablet" demandPopin="true"><Text text="Last Name" /></Column><Column minScreenWidth="Tablet" demandPopin="true"><Text text="Mobile No" /></Column></columns><items><ColumnListItem type="Active" press="onRowPress" vAlign="Middle"><cells><Text text="{patients>PID}" /><Text text="{patients>FNAME}" /><Text text="{patients>LNAME}"/><Text text="{patients>MOBNO}" /></cells></ColumnListItem></items></Table></VBox></Panel></content></Page></mvc:View>\n',
	"pmsopenui5test/pmsopenui5test/view/View_Main.view.xml":'<mvc:View controllerName="pmsopenui5test.pmsopenui5test.controller.View_Main"\n\txmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n\txmlns:l="sap.ui.layout"\n\txmlns:f="sap.ui.layout.form"\n\txmlns="sap.m"><Page id="page" title="Patient Management Home"><Panel headerText="Welcome to Patient Manager" class="sapUiResponsiveMargin" width="auto"><VBox class="sapUiSmallMargin"><l:Grid containerQuery="true" defaultSpan="L2 M6 S12"><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Create Patient" subheader="Create patient in system" press="CreatePatient" url="https://www.sap.com/"><TileContent><ImageContent src="sap-icon://flight" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="View Patient" subheader="Search a Patient" press="ViewPatient" url="https://www.sap.com/"><TileContent><ImageContent src="sap-icon://retail-store-manager" /></TileContent></GenericTile></l:Grid></VBox></Panel></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
